version: "3.9"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: "budget"
      POSTGRES_USER: "budget"
      POSTGRES_PASSWORD: "budget"
    ports:
      - "5432:5432"
    restart: unless-stopped
