version: "3.9"

services:
  client:
    build:
      context: ./client
    image: valentinalekhin/budget-client
    ports:
      - "3010:3000"
    environment:
      - TZ=Europe/Moscow
      - BASE_URL=11.5.0.6:3000
    networks:
      - net
    depends_on:
      - server
    restart: unless-stopped

  server:
    build:
      context: ./server
    image: valentinalekhin/budget-server
    environment:
      - TZ=Europe/Moscow
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - PORT=3000
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - ACCESS_TOKEN_EXPIRATION=${ACCESS_TOKEN_EXPIRATION}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - REFRESH_TOKEN_EXPIRATION=${REFRESH_TOKEN_EXPIRATION}
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_ADMIN=${BOT_ADMIN}
    networks:
      net:
        ipv4_address: 11.5.0.6
    ports:
      - "3011:3000"
    restart: unless-stopped

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 11.5.0.0/16
          gateway: 11.5.0.1