version: "3.9"

services:
  client:
    build:
      context: ./client
    image: valentinalekhin/budget-client
    ports:
      - "80:80"
    environment:
      - TZ=Europe/Moscow
    depends_on:
      - server
    restart: unless-stopped

  server:
    build:
      context: ./server-go
    image: valentinalekhin/budget-server
    environment:
      - TZ=Europe/Moscow
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - PORT=3000
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - ACCESS_TOKEN_EXPIRATION=${ACCESS_TOKEN_EXPIRATION}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - REFRESH_TOKEN_EXPIRATION=${REFRESH_TOKEN_EXPIRATION}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_BOT_ADMIN=${TELEGRAM_BOT_ADMIN}
    restart: unless-stopped

