import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Layout from '../layouts/default'
import { createTheme, ThemeProvider } from '@mui/material/styles'
import CssBaseline from '@mui/material/CssBaseline'
import { SessionProvider } from 'next-auth/react'
import { SnackbarProvider } from 'notistack'
import Head from 'next/head'
import { RecoilRoot } from 'recoil'

import '@fontsource/roboto/300.css'
import '@fontsource/roboto/400.css'
import '@fontsource/roboto/500.css'
import '@fontsource/roboto/700.css'

const theme = createTheme({
  palette: {
    primary: {
      main: '#5EB5F7',
      contrastText: '#f1faee',
    },
    secondary: {
      main: '#5EB5F7',
      light: '#e63946',
      dark: '#e63946',
    },
    background: {
      default: '#0E1621',
      paper: '#0E1621',
    },
    error: {
      main: '#e63946',
    },
    text: {
      primary: '#F5F5F5',
      secondary: '#f1faee',
    },
    info: {
      main: '#5EB5F7',
    },
    success: {
      main: '#5EB5F7',
    },
  },
})

function MyApp({ Component, pageProps: { session, ...pageProps } }: AppProps) {

  return (
    <SessionProvider session={session}>
      <RecoilRoot>
        <ThemeProvider theme={theme}>
          <SnackbarProvider
            dense
            maxSnack={3}
            anchorOrigin={{
              vertical: 'bottom',
              horizontal: 'right',
            }}>
            <CssBaseline/>
            <Head>
              <title>Budget</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
              <Component {...pageProps} />
            </Layout>
          </SnackbarProvider>
        </ThemeProvider>
      </RecoilRoot>
    </SessionProvider>
    )
}

export default MyApp

