name: Build and deploy

on:
  push:
    branches:
      - 'main'
      - 'dev'

jobs:
  build-server:
    name: Build and push server image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push server-go
        uses: docker/build-push-action@v3
        with:
          push: true
          context: "{{defaultContext}}:server-go"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/budget-server-go:${GITHUB_REF##*/}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/budget-server-go:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/budget-server-go:buildcache,mode=max

      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Repository: ${{ github.repository }}/server-go

            Server built

  build-client:
    name: Build and push client image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push client
        uses: docker/build-push-action@v3
        with:
          push: true
          context: "{{defaultContext}}:client"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/budget-client-dev:${GITHUB_REF##*/}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/budget-client-dev:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/budget-client-dev:buildcache,mode=max

      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Repository: ${{ github.repository }}/client

            Client deployed
